services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A celery_config.celery_app worker --loglevel=info
    depends_on:
      - redis
      - backend
    env_file:
      - .env
    volumes:
      - ./backend:/app

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery_beat
    # For start run
    command: >
      sh -c "
        celery -A celery_config.celery_app call src.tasks.fetch_and_save_latest_news &&
        celery -A celery_config.celery_app beat --loglevel=info
      "
    depends_on:
      - redis
      - celery_worker
      - backend
    env_file:
      - .env
    volumes:
      - ./backend:/app

volumes:
  mongodb_data:
